apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-stillingstitler
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  port: 4000
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/is_alive
    initialDelay: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 10
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
  ingresses:
    {{#each ingress}}
    - {{this}}
    {{/each}}
  env:
    - name: PAM_URL
      value: http://pam-ontologi.teampam
  accessPolicy:
    outbound:
      rules:
        - application: pam-ontologi
          namespace: teampam
    inbound:
      rules:
        - application: tiltaksgjennomforing
        - application: tiltaksgjennomforing-intern
        {{#each extra-inbound-apps}}
        - application: {{this}}
        {{/each}}
